# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-ctx',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/llm-ctx',
                'lib_path': 'llm_ctx'},
  'syms': { 'llm_ctx.core': { 'llm_ctx.core.Doc': ('core.html#doc', 'llm_ctx/core.py'),
                              'llm_ctx.core.Section': ('core.html#section', 'llm_ctx/core.py'),
                              'llm_ctx.core._parse_links': ('core.html#_parse_links', 'llm_ctx/core.py'),
                              'llm_ctx.core.get_sizes': ('core.html#get_sizes', 'llm_ctx/core.py'),
                              'llm_ctx.core.llms_txt2ctx': ('core.html#llms_txt2ctx', 'llm_ctx/core.py'),
                              'llm_ctx.core.mk_ctx': ('core.html#mk_ctx', 'llm_ctx/core.py'),
                              'llm_ctx.core.parse_llm_txt': ('core.html#parse_llm_txt', 'llm_ctx/core.py')}}}
